spring.application.name=lostpet
spring.datasource.url=jdbc:mysql://localhost:3306/lostpetfinder_db
spring.datasource.username=root
spring.datasource.password=sri777
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
